# Generated by Django 5.2.8 on 2026-02-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
