# Generated by Django 5.2.8 on 2026-03-13 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_job_created_at'),
        ('freelancers', '0006_alter_proposal_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted for Review'), ('revision', 'Needs Revision'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_hired', to='clients.clientprofile')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_working', to='freelancers.freelancerprofile')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='clients.job')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='freelancers.proposal')),
            ],
        ),
    ]
