# Generated by Django 5.2.8 on 2026-02-17 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0002_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='delivery_time',
        ),
    ]
