# Generated by Django 5.2.8 on 2026-03-06 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0003_remove_proposal_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_sent', to='freelancers.freelancerprofile'),
        ),
    ]
